### PR TITLE
feat: added Nth Node From Linkedlist End Program -> Java

### PR DESCRIPTION
**Pull request by HarshitPachori**
# SkillShow! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/SkillShow/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [ ] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by HarshitPachori** [comment]
Hi @Kushal997-das , Please review my PR and add hacktoberfest and hacktoberfest-accepted label to it.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@HarshitPachori Kindly update data.json file.

**Comment by HarshitPachori** [comment]
Hey @Kushal997-das , I have updated the data.json file . You can now review my PR.

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@HarshitPachori Mention your issue number.

**Comment by HarshitPachori** [comment]
Fixes #132

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
