### PR TITLE
Added my project

### PR DESCRIPTION
**Pull request by AvidCoder101**
# SkillShow! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/SkillShow/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

Added my project and username for hacktoberfest

### 🔧 Fixes #issue_no *(Required)*

#32  

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [ ] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@Kushal997-das please ignore the unnecessary commits, my other pull request became very messy as well, I hope this is better

**Comment by Kushal997-das** [comment]
@AvidCoder101 Mention issue number.

**Comment by AvidCoder101** [comment]
#32

**Comment by AvidCoder101** [comment]
@Kushal997-das Added the issue number

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@AvidCoder101 Kindly resolve the conflicts.

**Comment by AvidCoder101** [comment]
@Kushal997-das resolved merge conflicts

**Pull request merged**
